runtime: nodejs18
env: standard

handlers:
- url: /icons
  static_dir: www/icons
- url: /flightPaths
  script: auto
- url: /api/*
  script: auto
- url: /fakeapi
  static_files: www/api.html
  mime_type: text/html
  upload: www/api.html
- url: /madrug2
  static_files: www/madrug2.html
  mime_type: text/html
  upload: www/madrug2.html
- url: /madrug
  static_files: www/madrug.html
  mime_type: text/html
  upload: www/madrug.html
- url: /mapa
  static_files: www/mapa.html
  mime_type: text/html
  upload: www/mapa.html
- url: /.*
  static_files: www/index.html
  mime_type: text/html
  upload: www/index.html
