runtime: nodejs18
env: standard

handlers:
- url: /api
  static_files: api.html
  mime_type: text/html
  upload: api.html
- url: /.*
  static_files: index.html
  mime_type: text/html
  upload: index.html

