runtime: nodejs18
env: standard

handlers:
- url: /api/*
  script: auto
- url: /fakeapi
  static_files: www/api.html
  mime_type: text/html
  upload: www/api.html
- url: /.*
  static_files: www/index.html
  mime_type: text/html
  upload: www/index.html

