name: Deploy static web app to Azure Web App - nearbyaircraft

on:
  push:
    branches:
      - az
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: List root directory contents
        run: ls -al

      - name: List contents of nearbyaircraft directory
        run: |
          if [ -d "nearbyaircraft" ]; then
            ls -al nearbyaircraft
          else
            echo "Directory nearbyaircraft does not exist."
            exit 1
          fi

      - name: Zip artifact for deployment
        run: |
          cd nearbyaircraft
          zip -r release.zip www

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: static-app
          path: nearbyaircraft/release.zip

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: static-app

      - name: Unzip artifact for deployment
        run: unzip nearbyaircraft/release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B8761A00D6A948449D1010BCD6A4561C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_42EF1633D17D4E8F8FFD8D0BD2CF7817 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9A5E2448D7214C72AFAB27C51420F993 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'nearbyaircraft'
          slot-name: 'Production'
          package: .
