name: Deploy static web app to Azure Web App - nearbyaircraft

on:
  push:
    branches:
      - az
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Zip artifact for deployment
        run: zip release.zip -r www

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: static-app
          path: release.zip

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: static-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'nearbyaircraft'
          slot-name: 'Production'
          package: .

          
